### ISSUE TITLE
'다', '요' 외의 다른 끝음절 요청

### ISSUE THREAD

**Issue by nomota** [likejazz/korean-sentence-splitter#2]
코드에 보면, '다', '요'를 예외처리 하셔서, 문장 끝을 인식했는데, 실제로 문장의 끝은 그것 외에 더 다양하게 끝나잖아요. 마침형 문장부호 (. ? !)와 이런 끝 글자들이 조합되면, 문장의 끝으로 봐도 될 것 같습니다만...

예를 들어 '~함. ', '~(했)음. ', '~(나)감. ', '~(나)옴. ', '~(보)냄. ', '~(하)기. ', '~(랄)까. ', '~(카)노. ', '~(하)오. ', '~(이)지. ', '~냐. ' 이런 끝 글자들을 좀 폭 넓게 받아 주면 더 좋을 것 같습니다. 

또는 점세개(...)로 끝난다거나...

그 외에도 마침부호(. ? !)와 같이 나타나면 다 잘라 줄 수 있을 거 같습니다. 특히 이런 한글 + 마침 부호(. ? !) 다음에 공백(' ', '\t', '\n')이 오면 백프로 문장 끝으로 봐도 될 것 같습니다. 
'~(까)요? ', '~나. ', '~까? ', '~(뭔)가? ', '~(느)낌. ', '~뿐. ', '~(때문)에. ', '~뜻. '

페이스 친구들 포스팅에서 한 10분 정도 눈 대중으로 찾아보면, 이런 문장 끝 패턴들이 나옵니다. 이것들은 현재의 kss 에서는 분리가 안되고 연결되어 나오는 것 같습니다.

**Comment by likejazz** [comment]
이미 `.?!`와 끝 글자 조합을 문장의 끝으로 처리하고 있습니다.
다만, 무작정 마침 부호가 온다고 종료할 수 없기 때문에 가능한 예외 없이 확실한 경우에만 처리하고 있으며, 보다 구체적인 사례를 남겨주시면 확인 후 반영해보도록 하겠습니다.

**Comment by likejazz** [comment]
Close issue because there's no additional feedback.
