### ISSUE TITLE
KSS 설치

### ISSUE THREAD

**Issue by icontrol98** [likejazz/korean-sentence-splitter#3]
먼저 KSS개발 해주셔서 감사의 말씀을 드립니다

kss패키지를 설치하기 위해 pip install kss 명령을 이용했는데 계속 설치에러가 다음과 같이 납니다.

command errored out with exit status.

자세한 것은 첨부파일에 있는 스크린샷을 참조해 주십시오.

현재 파이썬은 버전 3.7.6, 아나콘다 버전은 4.81을 쓰고 있습니다.

아마도 환경설정 문제인 것 같은데 제 수준에선 해결하기 어렵습니다.

감사합니다.

![kss](https://user-images.githubusercontent.com/53134663/72857814-192f9880-3d02-11ea-867a-0e080585eda0.png)

**Comment by likejazz** [comment]
현재 보유하고 있는 윈도우 머신이 없어 Linux/Mac 빌드만 테스트 하고 윈도우에서는 테스트를 못한 상태입니다. 아마 간단한 수정으로 가능할거 같은데요. 나중에 환경이 구성되어야만 수정이 가능할거 같습니다. 혹시 수정 패치를 보내주실 수 있다면 고맙겠습니다.

**Comment by sypark9646** [comment]
@icontrol98 @likejazz 

저는 windows10 사용자인데, 
kss.tar.gz 파일을 다운로드 받아서 압축 해제 후 setup.py에 

`# Build params for each platforms.
if platform.system() == 'Linux':
    extra_compile_args=['-std=c++11']
    extra_link_args=[]
elif platform.system() == 'Darwin':
    extra_compile_args=['-std=c++11', '-stdlib=libc++']
    extra_link_args=['-stdlib=libc++']
`
아래 코드를 추가 후 python setup.py install --record files.txt 명령어를 사용하니까 되는 것 같아요.
'elif platform.system() == 'Windows':
    extra_compile_args=['/utf-8']
    extra_link_args=[]'

**Comment by likejazz** [comment]
@sypark9646 감사합니다.
알려주신대로 적용하여 윈도우에서 빌드되는거 확인하였습니다.
버전 1.3.0으로 업데이트하여 올려두었습니다.

단, 윈도우에 설치하기 위해서는 Cython과 Microsoft Visual C++ Build Tools가 필요합니다.
다시 한 번 감사합니다.
