### ISSUE TITLE
양쪽 따옴표 쌍이 안맞거나, 따옴표 수가 홀수인 문구가 등장하면 문장 분리가 되지 않는 경우들이 있습니다.

### ISSUE THREAD

**Issue by donghyeonk** [likejazz/korean-sentence-splitter#4]
안녕하세요 박상길님,

한국어 처리에 필수적인, 문장 분리 코드를 공개해주신 점 감사합니다.

다음은 문장 분리가 되지 않는 경우 예제들입니다. 

예제 1) 양쪽 따옴표 쌍이 안맞는 문구
우리 팀 촬영 PD는 “지금까지 탔던 차 중에 가장 편했다"라고 말했다. 이런 쉐슬람 같은! 아니다.
http://www.autoview.co.kr/content/article.asp?num_code=69736&news_section=car_ride&pageshow=3

예제 2) 양쪽 따옴표 쌍이 안맞는 문구
연비테스트를 진행하면서 들었던 의문점인 ‘트립 컴퓨터 정보'에 대한 신뢰도 문제였다. 3대의 차량 모두 연료를 더 이상 들어가지 않을 때 까지 가득 주유한 뒤 193km를 이동했다.
http://www.autoview.co.kr/content/article.asp?num_code=53652&news_section=car_r

예제 3) 따옴표 수가 홀수인 문구 (1개)
과거 씨드(Cee'd)를 시승하면서 만족감을 표한바 있다면 이제 내수시장서 판매되는 포르테 쿱에서 만족감을 표할 수 있게 되었다. 연비는 일반 주행을 기준으로 10km/L 정도를 예상하는 것이 좋다. 
http://www.autoview.co.kr/content/buyer_guide/guide_road_article.asp?num_code=32587&news_section=car_ride&pageshow=3

이 문제와 이어지는 다른 문제점은 이후 텍스트들이 문장분리가 되지 않고 끝까지 한 문장으로 인식된다는 점입니다.

전처리로 따옴표들을 일치시켜보면 (ex. “ -> ", ” -> ") 예제 1번과 2번 경우는 사라지지만 예제 3번 같은 경우는 해결되지 않고 남아있습니다.

감사합니다. 좋은 하루 보내세요.

**Comment by likejazz** [comment]
@donghyeonk 
감사합니다. 1) 2) 3) 모든 케이스에 대해 패치 완료 하였습니다.

따옴표 처리는 비슷한 형태의 잘못된 케이스에 대해서도 보정이 가능하도록 single/double quotes 단위로 그룹핑 하였고, 단일 single quote(`'`)에 대해서는 `He's`, `She's`, `I'm` 정도는 bypass하도록 패치하였습니다. 현재 알려주신 1) 2) 3) 모든 케이스에 대해 정상적으로 수행됩니다.

1.3.0으로 버전업 하여 올려두었습니다.
다시 한 번 감사합니다.
