### ISSUE TITLE
segmentation fault when passing english text

### ISSUE THREAD

**Issue by steremma** [likejazz/korean-sentence-splitter#5]
Some of my text (~1%) includes un-detected english content in otherwise korean corpuses. In the worst case I would expect the package to do nothing, however I get a `segmentation fault` and the program dies.

Example:

```
>>> import kss
>>> s = "The reason I booked this hostel was there'a a only for women's room. But my room was mixed room that doesn't have partitions or curtains. I claimed and asked for changing the room but there's no extra bed for me in only women's room. So I stayed other place 1st day."
>>>
>>> kss.split_sentences(s)
Segmentation fault (core dumped)
```

I am using Python 3 on Ubuntu 18

**Comment by likejazz** [comment]
@steremma Thanks for your bug reporting.

I had patched significant problem related with single quotation mark and have updated version number to 1.3.1 from 1.3.0.

Check out the new version.
Thanks.
