### ISSUE TITLE
' 또는 ’ 다음에 오는 문장들이 전부 다 하나의 문장으로 인식됩니다.

### ISSUE THREAD

**Issue by Dorurung** [likejazz/korean-sentence-splitter#8]
특히 예시1 (’가 포함) 같은 경우는 예전 버전(1.2.5)에선 잘 분리가 되었는데 현재 버전(1.3.1)에서 안 되었습니다.

### 입력 문서:
부부 싸움 규칙 가운데 ‘돈 히트 언더 더 벨트’(Don’t hit under the belt)가 있다. 권투할 때 벨트 아래를 치면 반칙이듯이, 상대가 너무 아파할 만한 것을 건드리면 회복하기 어렵다. 그 부분은 사람마다 다르다.

### 출력 결과(1.3.1):
(입력 문서와 동일)

### 출력 결과(1.2.5):
부부 싸움 규칙 가운데 ‘돈 히트 언더 더 벨트’(Don’t hit under the belt)가 있다.
권투할 때 벨트 아래를 치면 반칙이듯이, 상대가 너무 아파할 만한 것을 건드리면 회복하기 어렵다.
그 부분은 사람마다 다르다.

## 예시2)
입력 문서:
삼성전자가 11월 13일 삼성전자 서초사옥 다목적홀 5층에서 진행되는 2013 S'데이 멤버십 블루 강연회 "Challenge BLUE, 박찬호&이동우의 삶과 도전" 멤버십 블루 고객 480명을 초청한다.강연회는 삼성전자 멤버십 블루 회원들을 위해 마련된 고객 혜택 행사로 한국인 최초의 메이저리거 박찬호와 시각장애 개그맨 이동우를 초청, 그들의 삶 속에서 펼쳐진 다양한 도전기를 들을 수 있도록 마련했다.

### 출력 결과(1.2.5, 1.3.1 공통):
(입력 문서와 동일)

**Comment by hyunwoongko** [comment]
제가 이거 파이썬으로 포팅하면서 코드를 좀 봤는데, 이게 스택에 push, pop 하는 구조여서 '가 나온 다음에 다시 '가 나와야합니다. 위 문장의 경우 S'데이 라고 single quote를 열고나서 다시 닫는 quote가 없어서 그런 듯 하네요.

**Comment by hyunwoongko** [comment]
- https://github.com/likejazz/korean-sentence-splitter/blob/master/sentence_splitter.cpp#L121
- 제가 이거 파이썬으로 포팅하면서 코드를 좀 봤는데, 간단하게 규칙을 말씀드리면 '가 나온 다음에 반드시 다시 '가 나와야 잘 동작합니다. (즉 열고나서 반드시 닫아야합니다)
- 아마 예상컨데, quote 사이에 문장의 종결어미가 있는 경우에는 분절하지 않기 위해서 이렇게 구현하시지 않았을까 싶네요. 
- 가령 아래와 같은 문장이 있을 때, double quote 사이에서 분절해버리면 안되니까요.
  - `그는 "내가 다시 돌아온다고 말했니? 아니거든" 라고 말했다.`
  - 여기에서 `말했니?` 뒤에서 문장으로 분절해버리면 안되니까 이러한 처리가 필요합니다.
- 위 문장의 경우 S'데이 라고 single quote를 열고나서 다시 닫는 quote가 없어서 그렇게 동작한 듯 하네요.
- 음... 이게 통계나 뉴럴기반이 아니라 휴리스틱 기반이여서 이렇게 디테일한 부분까지 전부 다 해결하는 것은 꽤 어렵습니다.

**Comment by hyunwoongko** [comment]
아예 해결이 불가능 한 것은 아니고, 이 문제를 현재 구조에서 해결하려면 문장의 마지막까지 탐색을 완료했음에도 불구하고 quote가 열린 상태였다면 (스택의 길이가 0이 아닌 경우) 문장을 다시 불러온 뒤 마지막 quote가 등장한 지점까지 탐색 해서 문장을 refine 해주는 구조로 설계할 수 있을 것 같긴한데, 제가 파이썬 레포에서 작업해보고 공유드릴게요.

**Comment by hyunwoongko** [comment]
첫번째 경우에는 `‘돈 히트 언더 더 벨트’(Don’t hit under the belt)` 때문에 분절이 되지 않은 것이구요. 1.3.0으로 넘어가면서 n't, e's같이 자주 등장하는 어퍼스트로피에 대한 처리가 생겼는데 그 부분 때문에 이렇게 작동한 것 같네요. 이 부분은 위의 문제를 해결하면 자연스레 해결되는 부분이라서 작업한 뒤에 다시 공유드릴게요~

**Comment by hyunwoongko** [comment]
- https://github.com/hyunwoongko/python-kss
- 말씀하신 문제를 해결하여 업로드 하였습니다.
